// Package gochecks provide a monitoring checks engine to create or embbed
// small monitoring system that can publish the periodic check result to
// other monitoring plataforms
package gochecks

import (
	"time"

	"github.com/aleasoluciones/goaleasoluciones/scheduledtask"
)

// Check result event, very inspired and compatible with Riemann events
type Event struct {
	Host        string
	Service     string
	State       string
	Metric      interface{}
	Description string
	Tags        []string
	Attributes  map[string]string
	TTL         float32
}

// CheckEngine monitoring check engine to schedule periodics checks and publish
// the results
type CheckEngine struct {
	checkPublishers []CheckPublisher
	results         chan Event
}

// NewCheckEngine return a CheckEngine that publish the results of the
// periodic checks to the given publishers
func NewCheckEngine(publishers []CheckPublisher) *CheckEngine {
	checkEngine := CheckEngine{publishers, make(chan Event)}
	go func() {
		for result := range checkEngine.results {
			for _, publisher := range checkEngine.checkPublishers {
				publisher.PublishCheckResult(result)
			}
		}
	}()
	return &checkEngine
}

// AddResult publish the given check result as if it was generated by a
// scheduled check
func (ce *CheckEngine) AddResult(event Event) {
	ce.results <- event
}

// AddCheck schedule a new check to be executed with the given period
func (ce *CheckEngine) AddCheck(check CheckFunction, period time.Duration) {
	scheduledtask.NewScheduledTask(func() {
		ce.results <- check()
	}, period, 0)
}

// AddMultiCheck schedule a new multi check to be executed with the given period
// the muli check can return an array of events/results
func (ce *CheckEngine) AddMultiCheck(check MultiCheckFunction, period time.Duration) {
	scheduledtask.NewScheduledTask(func() {
		for _, result := range check() {
			ce.results <- result
		}
	}, period, 0)
}
